// Shared demo types (re-exported from the canonical shared/demo package).
// Canonical source: shared/demo/types.ts (one source of truth for desktop,
// mobile and the demo server).
export type {
  DomainId,
  TaskStatus,
  UrgencyGroup,
  AlertSourceKey,
  DocumentStatus,
  EvidenceStatus,
  EvidenceType,
  EvidenceMetadata,
  EvidenceItem,
  UserRef,
  FormFieldSpec,
  FormSpec,
  EscalationEvent,
  ClosureCertificate,
  Task,
  MineSite,
  Alert,
  AuditEvent,
  DocumentPipeline,
  PipelineState,
  ObligationRule,
  DemoState,
  MobileState,
} from '../../shared/demo/types';
