"""RagService — orchestrates the SAMAADHAN advisory (RAG) layer.

Responsibilities:
- index the 18-document corpus from ``data/rag/RAG_CORPUS.md`` (+ local text),
- retrieve similar regulatory passages for a question / an incoming instrument,
- surface **organizational memory** (past obligations with the same pattern) with a
  deterministic advisory line, and
- answer questions with citations, either via a real Gemini call or via the
  deterministic extractive fallback.

Honesty invariant (matches the demo story): everything served here is labelled
**advisory**. Rules and human review decide compliance; this layer only retrieves
and summarises.
"""
from __future__ import annotations

import logging
from datetime import datetime, timezone

import httpx
from sqlalchemy import func, select

from app.config import Settings
from app.database import Database
from app.services.rag.chunking import chunk_text
from app.services.rag.corpus import CORPUS, CorpusDocument, corpus_root
from app.services.rag.embeddings import EmbeddingProvider, GeminiEmbedder, build_embedder
from app.services.rag.models import RagDocument, RagMemory
from app.services.rag.store import RagVectorStore
from app.services.rag.text_extraction import extract_document_text

logger = logging.getLogger(__name__)

DISCLAIMER = (
    "Advisory only — generated by SAMAADHAN's retrieval layer. Rules and human "
    "verification decide compliance; AI output never creates or closes an obligation."
)

# Default organizational-memory corpus (seed): past obligations for the five-mine
# area, used by the memory/advisory panel and parity tests. Labels & delays match
# the demo story (DEMO_FLOW.md scene 4 / scene 10).
DEFAULT_MEMORY: list[dict] = [
    {
        "memory_key": "MEM-ASHOKA-SLOPE-FY2023",
        "mine_id": "MINE-002",
        "mine_name": "Ashoka OCP",
        "label": "FY2023 weekly slope-displacement monitoring (highwall)",
        "pattern_codes": ["SLOPE", "WEEKLY", "HIGHWALL", "EXTENSOMETER", "DISPLACEMENT"],
        "description": "Weekly extensometer + prism monitoring of a 38 m highwall; closed 12 days after deadline.",
        "outcome": "closed_late",
        "delay_days": 12,
        "evidence_notes": "Extensometer reading sheet and crest photos submitted after escalation reminder.",
        "source_ref": "org-memory seed (DEMO_FLOW.md scene 4)",
    },
    {
        "memory_key": "MEM-MAGADH-SLOPE-FY2024",
        "mine_id": "MINE-003",
        "mine_name": "Magadh OCP",
        "label": "FY2024 weekly slope-displacement monitoring (highwall)",
        "pattern_codes": ["SLOPE", "WEEKLY", "HIGHWALL", "EXTENSOMETER", "DISPLACEMENT"],
        "description": "Same weekly obligation on a 42 m highwall bench; closed 9 days after deadline.",
        "outcome": "closed_late",
        "delay_days": 9,
        "evidence_notes": "Closed late because the second evidence photo was rejected once (berm markers missing).",
        "source_ref": "org-memory seed (DEMO_FLOW.md scene 4)",
    },
    {
        "memory_key": "MEM-PIPARWAR-SLOPE-FY2024",
        "mine_id": "MINE-001",
        "mine_name": "Piparwar OCP",
        "label": "FY2024 weekly slope-displacement monitoring (Bench 3B highwall)",
        "pattern_codes": ["SLOPE", "WEEKLY", "HIGHWALL", "EXTENSOMETER", "DISPLACEMENT"],
        "description": "Weekly monitoring on Bench 3B closed on time across 41 consecutive weekly instances.",
        "outcome": "closed_on_time",
        "delay_days": 0,
        "evidence_notes": "Consistent geo-tagged extensometer readings; no rejection in FY2024.",
        "source_ref": "org-memory seed",
    },
    {
        "memory_key": "MEM-AMRAPALI-DUST-FY2024",
        "mine_id": "MINE-005",
        "mine_name": "Amrapali OCP",
        "label": "FY2024 haul-road dust-suppression water-sprinkling compliance",
        "pattern_codes": ["DUST", "PM10", "SPRINKLER", "HAULROAD", "WEEKLY"],
        "description": "Weekly haul-road sprinkling log vs EC Condition 14 PM10 limit; closed late once.",
        "outcome": "closed_late",
        "delay_days": 4,
        "evidence_notes": "Sprinkler coverage gaps during dry shifts; corrective log added after rejection.",
        "source_ref": "org-memory seed",
    },
    {
        "memory_key": "MEM-RAYBACHRA-CLRA-FY2025",
        "mine_id": "MINE-004",
        "mine_name": "Ray-Bachra UG",
        "label": "FY2025 CLRA licence renewal documentation",
        "pattern_codes": ["CLRA", "RENEWAL", "LABOUR", "CONTRACTOR"],
        "description": "Contract-labour licence renewal filed with full muster and attendance registers.",
        "outcome": "closed_on_time",
        "delay_days": 0,
        "evidence_notes": "Register scans attached at first submission.",
        "source_ref": "org-memory seed",
    },
]


class RagService:
    def __init__(self, db: Database, settings: Settings) -> None:
        self._db = db
        self._settings = settings
        self._embedder: EmbeddingProvider = build_embedder(settings)
        self.store = RagVectorStore(db, self._embedder, vector_backend=settings.rag_vector_backend)
        self._data_dir = settings.resolved_rag_data_dir
        self._ready = False

    @property
    def embedder(self) -> EmbeddingProvider:
        return self._embedder

    # ---- lifecycle ------------------------------------------------------------

    async def ensure_ready(self) -> None:
        if self._ready:
            return
        await self.store.ensure_schema()
        await self._seed_memory_if_empty()
        self._ready = True
        if self._settings.rag_auto_index_on_start:
            counts = await self.store.counts()
            if counts["documents_indexed"] == 0:
                logger.info("rag: auto-index on start — building corpus index")
                await self.ingest_corpus(rebuild=False)

    async def _seed_memory_if_empty(self) -> None:
        memory_count = 0
        async for session in self._db.session():
            memory_count = (
                await session.execute(select(func.count()).select_from(RagMemory))
            ).scalar_one()
        if memory_count > 0:
            return
        texts = []
        for row in DEFAULT_MEMORY:
            texts.append(_memory_text(row))
        vectors = await self._embedder.embed_many(texts)
        for row, vector in zip(DEFAULT_MEMORY, vectors, strict=False):
            payload = {**row, "embedding": vector}
            await self.store.upsert_memory(payload)
        logger.info("rag: seeded %d organizational-memory entries", len(DEFAULT_MEMORY))

    # ---- corpus ingestion -----------------------------------------------------

    async def ingest_corpus(self, rebuild: bool = False) -> dict:
        await self.ensure_ready()
        if rebuild:
            await self.store.reset()
            # reset() wipes rag_memory too — reseed so the memory panel always has history.
            await self._seed_memory_if_empty()

        indexed: list[dict] = []
        skipped: list[dict] = []
        for doc in CORPUS:
            result = await self.ingest_document(doc)
            (indexed if result["status"] == "indexed" else skipped).append(result)
        counts = await self.store.counts()
        return {
            "mode": "rebuild" if rebuild else "incremental",
            "indexed": indexed,
            "skipped": skipped,
            "counts": counts,
        }

    async def ingest_document(self, doc: CorpusDocument) -> dict:
        text = await extract_document_text(self._data_dir, doc)
        meta = {
            "doc_id": doc.doc_id,
            "tier": doc.tier,
            "title": doc.title,
            "source_class": doc.source_class,
            "origin": doc.origin,
            "bundled_rel": doc.bundled_rel,
            "why_relevant": doc.why_relevant,
            "domain": doc.domain,
            "mine_relevance": doc.mine_relevance,
            "concepts": doc.concepts,
        }

        if not text.strip():
            await self.store.upsert_document({**meta, "status": "no_text", "char_count": 0, "chunk_count": 0})
            return {
                "doc_id": doc.doc_id,
                "title": doc.title,
                "status": "no_text",
                "detail": "URL-only document or extraction unavailable (drop text at data/rag/text/<doc_id>.txt to index)",
            }

        chunks = chunk_text(text, chunk_size=self._settings.rag_chunk_size)
        await self.store.delete_chunks(doc.doc_id)
        vectors = await self._embedder.embed_many(chunks) if chunks else []
        for seq, (content, vector) in enumerate(zip(chunks, vectors, strict=False)):
            await self.store.add_chunk(
                chunk_key=f"{doc.doc_id}:{seq}",
                doc_id=doc.doc_id,
                seq=seq,
                content=content,
                meta={"heading": content[:120]},
                embedding=vector,
            )
        await self.store.upsert_document(
            {
                **meta,
                "status": "indexed",
                "char_count": len(text),
                "chunk_count": len(chunks),
                "indexed_at": datetime.now(timezone.utc),
            }
        )
        logger.info("rag: indexed %s (%d chars -> %d chunks)", doc.doc_id, len(text), len(chunks))
        return {"doc_id": doc.doc_id, "title": doc.title, "status": "indexed", "chunks": len(chunks)}

    # ---- queries ----------------------------------------------------------------

    async def status(self) -> dict:
        counts = await self.store.counts()
        return {
            "embedding_backend": self._embedder.name,
            "embedding_dim": self._embedder.dim,
            "generation_mode": "gemini" if self._settings.gemini_enabled else "extractive-fallback",
            "vector_backend": self.store.backend,
            "corpus_root": str(corpus_root(self._data_dir)),
            "counts": counts,
            "disclaimer": DISCLAIMER,
        }

    async def list_documents(self) -> list[dict]:
        async for session in self._db.session():
            rows = (await session.execute(select(RagDocument))).scalars().all()
        return [
            {
                "doc_id": d.doc_id,
                "title": d.title,
                "source_class": d.source_class,
                "origin": d.origin,
                "domain": d.domain,
                "mine_relevance": d.mine_relevance or [],
                "concepts": d.concepts or [],
                "why_relevant": d.why_relevant,
                "status": d.status,
                "chunk_count": d.chunk_count,
            }
            for d in rows
        ]

    async def _filtered_doc_ids(self, mine_id: str | None, domain: str | None, concepts: list[str] | None) -> set[str] | None:
        docs = await self.list_documents()
        ids: set[str] = set()
        for d in docs:
            if mine_id and mine_id not in (d["mine_relevance"] or []):
                continue
            if domain and domain.lower() not in (d["domain"] or "").lower():
                continue
            if concepts and not any(c.lower() in " ".join(d["concepts"] or []).lower() for c in concepts):
                continue
            ids.add(d["doc_id"])
        return ids or None

    async def search(
        self,
        query: str,
        top_k: int = 8,
        mine_id: str | None = None,
        domain: str | None = None,
        concepts: list[str] | None = None,
    ) -> dict:
        query_vector = await self._embedder.embed(query)
        doc_ids = await self._filtered_doc_ids(mine_id, domain, concepts)
        hits = await self.store.search_chunks(
            query_vector, top_k=top_k, doc_ids=doc_ids, query_text=query
        )
        docs = {d["doc_id"]: d for d in await self.list_documents()}
        results = []
        for hit in hits:
            doc = docs.get(hit["doc_id"], {})
            results.append(
                {
                    "chunk_key": hit["chunk_key"],
                    "score": hit["score"],
                    "snippet": _snippet(hit["content"]),
                    "doc_id": hit["doc_id"],
                    "title": doc.get("title", ""),
                    "source_class": doc.get("source_class", ""),
                    "origin": doc.get("origin", ""),
                    "why_relevant": doc.get("why_relevant", ""),
                    "domain": doc.get("domain", ""),
                    "mine_relevance": doc.get("mine_relevance", []),
                    "concepts": doc.get("concepts", []),
                }
            )
        return {
            "query": query,
            "mode": "retrieval",
            "embedding_backend": self._embedder.name,
            "vector_backend": self.store.backend,
            "top_k": len(results),
            "results": results,
            "disclaimer": DISCLAIMER,
        }

    async def memory_lookup(
        self,
        pattern: str,
        codes: list[str] | None = None,
        mine_id: str | None = None,
        top_k: int = 5,
    ) -> dict:
        """Organizational-memory retrieval + deterministic advisory line."""
        text = " ".join((codes or []) + [pattern])
        query_vector = await self._embedder.embed(text)
        matches = await self.store.search_memory(query_vector, top_k=top_k, mine_id=mine_id)
        advisory = _build_memory_advisory(pattern, matches)
        return {
            "pattern": pattern,
            "codes": codes or [],
            "matches": matches,
            "advisory": advisory,
            "mode": "memory" if self._embedder.name == "local" else "memory-vector",
            "embedding_backend": self._embedder.name,
            "disclaimer": DISCLAIMER,
        }

    async def ask(
        self,
        query: str,
        top_k: int = 6,
        mine_id: str | None = None,
        domain: str | None = None,
    ) -> dict:
        """Retrieval-augmented answer with citations (Gemini or extractive fallback)."""
        retrieval = await self.search(query, top_k=top_k, mine_id=mine_id, domain=domain)
        results = retrieval["results"]

        if not results:
            return {
                "query": query,
                "answer": (
                    "No passage in the current corpus matches this question. The corpus covers the "
                    "bundled regulatory instruments and area documents in data/rag/."
                ),
                "mode": "extractive-fallback",
                "citations": [],
                "disclaimer": DISCLAIMER,
            }

        if self._settings.gemini_enabled:
            answer, ok = await self._generate_gemini(query, results)
            if ok:
                return {
                    "query": query,
                    "answer": answer,
                    "mode": "generative",
                    "model": self._settings.gemini_generation_model,
                    "citations": [_citation(r) for r in results],
                    "disclaimer": DISCLAIMER,
                }

        answer = _extractive_answer(query, results)
        return {
            "query": query,
            "answer": answer,
            "mode": "extractive-fallback",
            "citations": [_citation(r) for r in results],
            "disclaimer": DISCLAIMER,
        }

    # ---- generation ---------------------------------------------------------------

    async def _generate_gemini(self, query: str, results: list[dict]) -> tuple[str, bool]:
        context_blocks = []
        for i, r in enumerate(results, start=1):
            context_blocks.append(
                f"[{i}] {r['title']} ({r['source_class']})\nSource: {r['origin']}\n"
                f"Domain: {r['domain']}\nWhy relevant: {r['why_relevant']}\n"
                f"Passage: {r['snippet']}"
            )
        context = "\n\n".join(context_blocks)
        system = (
            "You are the advisory retrieval assistant inside SAMAADHAN, a coal-mine compliance "
            "platform. Answer ONLY from the provided passages. Cite each claim with [n]. If the "
            "passages do not answer the question, say so. Never invent regulations. Never decide "
            "compliance — end with: 'Advisory only. Rules and human verification decide compliance.'"
        )
        user_prompt = f"Question: {query}\n\nPassages:\n{context}"
        url = (
            "https://generativelanguage.googleapis.com/v1beta/"
            f"models/{self._settings.gemini_generation_model}:generateContent"
        )
        headers = {"x-goog-api-key": self._settings.gemini_api_key}
        payload = {
            "contents": [{"role": "user", "parts": [{"text": f"{system}\n\n{user_prompt}"}]}],
            "generationConfig": {"temperature": 0.2, "maxOutputTokens": 900},
        }
        try:
            async with httpx.AsyncClient(timeout=45) as client:
                resp = await client.post(url, json=payload, headers=headers)
                resp.raise_for_status()
                data = resp.json()
            text_out = data["candidates"][0]["content"]["parts"][0]["text"]
            return text_out.strip(), True
        except Exception as exc:  # noqa: BLE001 — degrade to extractive fallback
            logger.warning("rag: gemini generation failed (%s) — extractive fallback", exc)
            return "", False


# ---- formatting helpers --------------------------------------------------------


def _memory_text(row: dict) -> str:
    return " ".join(
        (row.get("pattern_codes") or [])
        + [row.get("label", ""), row.get("description", ""), row.get("outcome", "")]
    )


def _build_memory_advisory(pattern: str, matches: list[dict]) -> str:
    if not matches:
        return (
            f"Memory: no similar past obligation found for this pattern "
            f"(\"{pattern[:80]}\"). This looks like a first occurrence."
        )
    late = [m for m in matches if m.get("outcome") == "closed_late"]
    if late:
        detail = "; ".join(
            f"{m['mine_name']} ({m.get('label', '')[:40]}) closed D+{m.get('delay_days') or '?'}"
            for m in late[:3]
        )
        return (
            f"Memory: a similar pattern ({pattern[:80]}) closed late before — {detail}. "
            "Advisory: keep the cadence but schedule this instance early and expect at least one "
            "verifier rejection; verify evidence completeness before submission."
        )
    on_time = [m for m in matches if m.get("outcome") == "closed_on_time"]
    if on_time:
        names = ", ".join(m["mine_name"] for m in on_time[:3])
        return (
            f"Memory: similar pattern ({pattern[:80]}) previously closed on time at {names}. "
            "Advisory: follow the same evidence routine."
        )
    return f"Memory: {len(matches)} similar past obligations found for this pattern. Advisory: review cadence and evidence checklist."


def _snippet(content: str, limit: int = 500) -> str:
    content = " ".join(content.split())
    return content[:limit] + ("…" if len(content) > limit else "")


def _citation(r: dict) -> dict:
    return {
        "doc_id": r["doc_id"],
        "title": r["title"],
        "source_class": r["source_class"],
        "origin": r["origin"],
        "domain": r["domain"],
        "why_relevant": r["why_relevant"],
        "score": r["score"],
        "quote": r["snippet"],
    }


def _extractive_answer(query: str, results: list[dict]) -> str:
    lines = [
        "Advisory answer (deterministic extractive mode — no LLM call). "
        f"The closest passages in the SAMAADHAN corpus for “{query}” are:"
    ]
    for i, r in enumerate(results[:4], start=1):
        lines.append(f"{i}. {r['title']} [{r['source_class']}] — {r['why_relevant']}")
        lines.append(f"   “{r['snippet'][:260]}”")
    lines.append("Read the full source documents (citations below) before acting. "
                 "Rules and human verification decide compliance.")
    return "\n".join(lines)
